server:
  port: 13145  # 默认端口
  tomcat:
    uri-encoding: UTF-8 # 默认编码
spring:
  application:
    name: eureka # 项目名称
eureka:
  server:
    enableSelfPreservation: false #自我保护模式 eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除。true为不删除、false为删除
  client:
    registerWithEureka: false #是否注册到注册中心，默认为true
    fetchRegistry: false #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/ #注册中心地址